server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 200
      min-spare: 30
    connection-timeout: 5000ms
  port: 8080
  servlet:
    context-path: /emos-wx-api

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/emos?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
      username: root
      password: abc123456
      initial-size: 8
      max-active: 16
      min-idle: 8
      max-wait: 60000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

  redis:
    database: 0
    host: localhost
    port: 6379
    password: abc123456
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 16
        min-idle: 8

  data:
    mongodb:
      host: localhost
      port: 27017
      database: emos
      authentication-database: admin
      username: admin
      password: abc123456
  mail:
    default-encoding: UTF-8
    host: stmp.aliyun.com
    username: 2408574313@aliyun.com
    password: liangxiaorui123

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.emos.wx.db.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    com.example.emos.wx.db.dao : warn
  pattern:
    console: "%d{HH:mm:ss}  %-5level  %msg%n"

emos:
  jwt:
    secret: abc123456
    expire: 5
    cache-expire: 10
  face:
    createFaceModelUrl: http://运行人脸识别程序的主机IP:3000/create_face_model
    checkinUrl: http://运行人脸识别程序的主机IP:3000/checkin
  #常用邮箱列表
  email:
    system: 2408574313@aliyun.com
    hr: 2408574313@qq.com
  #缓存人脸签到照片的路径
  image-folder: D:/emos/image
  #《SpringBoot在线办公小程序》课程的慕课网授权码
  code: icode授权码
  recieveNotify: http://本地主机IP:8080/emos-wx-api/meeting/recieveNotify

workflow:
  url: http://本地主机IP:9090/emos-workflow


trtc:
  appid: 1400569024
  key: bff302dd2916662654e5acde37d0dd995987e265ca46d55d5201bb752bc9f7fe
  expire: 86400
wx:
  app-id: wxe2645691011d52b5
  app-secret: 882a21399bff7a183552f45d78b223ce